### ISSUE TITLE
mini mini typo...

### ISSUE THREAD

**Issue by fabrizioq** [jeffWelling/ticgit#15]
ticgit / lib / ticgit-ng / command.rb 
line 12: "Assigns" (g before n)
obviously not an issue, but i'm not a programmer (just user) and this is the best i could do to help... please delete this message.
best of luck.

**Comment by jeffWelling** [comment]
Oh my. Thanks for catching that. How embarrassing lol
Hey, every little bit helps :) even typos.
Fixed in commit  0bb541ae2b415a8448c4

**Comment by fabrizioq** [comment]
Thank You. All the best from Argentina!
