### ISSUE TITLE
ticgit repo branch should be created on `ti init` not `ti`

### ISSUE THREAD

**Issue by jeffWelling** [jeffWelling/ticgit#17]
Copied from https://github.com/schacon/ticgit/issues/#issue/3

Nobody (including me) expects a new branch to be created by simply typing ti. The standard is to use an init command. A very wide-spread convention in the ruby/git community. So it would be better to show some little hint or the command list instead.

**Comment by chriskempson** [comment]
+1 Just came here to post about this unusual behaviour.

**Comment by jeffWelling** [comment]
This behaviour has been fixed. Closing the issue.
