### ISSUE TITLE
codeset issue with ti list

### ISSUE THREAD

**Issue by sebastianstigler** [jeffWelling/ticgit#34]
Hi,

I'm using ti on debian 6 with the locale LANG=de_DE@euro. In this setting "ti list" prints, when the text in the respective column is to long instead of the ... literal some funny characters.  I've located the problem in lib / ticgit-ng / cli.rb. in line 205 and 217 (because you use probably some utf8 setting):

 sub_value = "#{value[0, size - 1]}\xe2\x80\xa6"

My workaround is to use the middle dot \xb7 instead of \xe2\x80\xa6:

 sub_value = "#{chars[0, size-1]}\xb7"

But I think that this should be done automatically.

**Comment by jeffWelling** [comment]
Hi, thanks for the feedback!
I admit that I'm unfamiliar with locale issues, but as soon as I have some free time I'll see what I can do to resolve this. Unfortunately I'm swamped with work at the moment, so that may not be for a week or two, but this shall be resolved. :)

**Comment by jeffWelling** [comment]
Hi again!
We ended up using replacing the elipsis with a + to get around this without having to check $LANG, it's fixed in version 1.0.2.10 which has been pushed to Rubygems.
Thanks for the feedback!
