### ISSUE TITLE
No unassigned state (or documentation clarification request)

### ISSUE THREAD

**Issue by emmanuelbernard** [jeffWelling/ticgit#35]
Hi,

I could not make a ticket unassigned. When creating a ticket, it is assigned to the creator by default. 

I imagine a fake name passed to `--user` would work. But I wonder whether it is the expected pattern or if the feature is currently missing.

A small hint in the doc would be nice.

**Comment by jeffWelling** [comment]
Hmm... Being able to effectively assign 'nobody' to a ticket seems like something that is very much within the norm.  I'll look into this, I thought it could already do that so if that's the case I'll document it, otherwise I'll add the feature.
Thanks for the feedback!

**Comment by jeffWelling** [comment]
I've found that you can assign a ticket to nobody by doing `ti assign -u ''`.
But your right, the documentation doesn't make that very clear so I'll make a note about that in `ti assign --help`.
Thanks,
Jeff.
