### ISSUE TITLE
cannot chose the port on ticgitweb

### ISSUE THREAD

**Issue by azimonti** [jeffWelling/ticgit#38]
Hello,
when I cannot force the port on sinatra server

 ticgitweb -p 1234

= Sinatra/1.0 has taken the stage on 4567 for development with backup from Thin

> > Thin web server (v1.3.1 codename Triple Espresso)
> > Maximum connections set to 1024
> > Listening on 0.0.0.0:4567, CTRL+C to stop

I am running it with ruby 1.8.7 an 1.9.2 on Mac OS

**Comment by jeffWelling** [comment]
Well that's certainly not the way that's supposed to behave, I'll see if I can track this peculiarity down, are you using Snow Leopard or Lion, or something prior?

**Comment by azimonti** [comment]
I am using the latest Lion (10.7.2).

An "hello world" program is working fine

```
require 'sinatra'

get '/' do
  "Hello World!"
end
```

[/tmp]$ ruby -rubygems test_sinatra.rb 
== Sinatra/1.0 has taken the stage on 4567 for development with backup from Thin

> > Thin web server (v1.3.1 codename Triple Espresso)
> > Maximum connections set to 1024
> > Listening on 0.0.0.0:4567, CTRL+C to stop
> > ^C>> Stopping ...

== Sinatra has ended his set (crowd applauds)
[/tmp]$ ruby -rubygems test_sinatra.rb -p 1234
== Sinatra/1.0 has taken the stage on 1234 for development with backup from Thin

> > Thin web server (v1.3.1 codename Triple Espresso)
> > Maximum connections set to 1024
> > Listening on 0.0.0.0:1234, CTRL+C to stop
> > ^C>> Stopping ...

== Sinatra has ended his set (crowd applauds)

**Comment by azimonti** [comment]
Hello,
i digged a bit more, and seem a problem is in the redirection script (the one in the path).

If I call the gem directly, it is working fine.
/Users/Marco/.rvm/gems/ruby-1.9.2-p290/gems/TicGit-ng-1.0.2.11/bin/ticgitweb -p 1234
Resetting cache
== Sinatra/1.0 has taken the stage on 1234 for development with backup from Thin

> > Thin web server (v1.3.1 codename Triple Espresso)
> > Maximum connections set to 1024
> > Listening on 0.0.0.0:1234, CTRL+C to stop
> > ^C>> Stopping ...

while, the executable in the path
ticgitweb -p 1234 (which is a short for /Users/Marco/.rvm/gems/ruby-1.9.2-p290/bin/ticgitweb -p 1234) does not work.
Resetting cache
== Sinatra/1.0 has taken the stage on 4567 for development with backup from Thin

> > Thin web server (v1.3.1 codename Triple Espresso)
> > Maximum connections set to 1024
> > Listening on 0.0.0.0:4567, CTRL+C to stop
> > ^C>> Stopping ...

thanks

**Comment by jandechent** [comment]
same for me on windows `ruby C:\Ruby193\lib\ruby\gems\1.9.1\gems\TicGit-ng-1.0.2.16\bin\ticgitweb -p 1234` works fine, but the full path has to be given.
