### ISSUE TITLE
complete ti list --help

### ISSUE THREAD

**Issue by azimonti** [jeffWelling/ticgit#40]
hello,
as the order ascending or descending is supported, can you add this information into the help?

currently

```
ti list --help
-o, --order ORDER                Field to order by - one of : assigned,state,date,title
```

proposed

```
ti list --help
-o, --order ORDER                Field to order by - one of : assigned,state,date,title [.desc for reverse order]
```

It is useful for a list order by date, as the default is to order by the less recent issue.

I found it in the code. :-)
https://github.com/jeffWelling/ticgit/blob/deving/lib/ticgit-ng/base.rb#L172

**Comment by jeffWelling** [comment]
Wow thanks! You've submitted a number of bug reports and I'd like to give you credit for your help, may I codify your name in one of the commit messages? Would you prefer that I use 'marcolinux', your real name, or another pseudonym?
Thanks again!

**Comment by azimonti** [comment]
Your welcome. No problems to use my real name in the commit messages, as it is nice to contribute to an useful project!

**Comment by jeffWelling** [comment]
This has been added to the latest release, thanks again!
