### ISSUE TITLE
bug on recomment

### ISSUE THREAD

**Issue by azimonti** [jeffWelling/ticgit#41]
Hello,

https://github.com/jeffWelling/ticgit/blob/deving/lib/ticgit-ng/command/recomment.rb#L28

there are 2 bugs
1- a misspell (options.messsage -> options.message)

(at least on my SO - Mac OS Lion) get_editor_message is an array, and get a cast error (cannot cast an Array in String).
I workaround it with get_editor_message[0]

thanks

**Comment by jeffWelling** [comment]
Hm, thanks for pointing this out.  As you probably already know that appears to be on the deving branch (recomment.rb is part of the code I wrote to help sync with other bug trackers, something that is still not yet finished), so I'll leave this open for now but I just wanted to note this isn't a bug against the master branch.
