### ISSUE TITLE
bug on tag command

### ISSUE THREAD

**Issue by azimonti** [jeffWelling/ticgit#42]
hello,
https://github.com/jeffWelling/ticgit/blob/deving/lib/ticgit-ng/command/tag.rb#L20

ti tag 705898 test
in this case, the code called is

```
elsif ARGV.size > 2 #tag 
      tic.ticket_tag(ARGV[2], nil, options)
```

-> ticket_id is nil -> is updating always the first ticket

should be

```
elsif ARGV.size > 2 #tag 
      tid = ARGV[1].chomp
      tic.ticket_tag(ARGV[2], tid, options)
```

thanks

**Comment by jeffWelling** [comment]
Thank you, this has just been fixed and will be in the coming version, 1.0.2.12. Thanks for reporting it!
