### ISSUE TITLE
Creating new ticket fails

### ISSUE THREAD

**Issue by nbigaouette** [jeffWelling/ticgit#43]
I just installed ticgit on Gentoo but I cannot use it. Running through the command line gives:

$ ti new
[edit the new ticket information, save and exit editor]
/usr/lib64/ruby/gems/1.8/gems/TicGit-ng-1.0.2.12/lib/ticgit-ng/ticket.rb:89:in `save_new': undefined method`info' for #IO:0x7f028d694ad8 (NoMethodError)
        from /usr/lib64/ruby/gems/1.8/gems/TicGit-ng-1.0.2.12/lib/ticgit-ng/base.rb:398:in `in_branch'
        from /usr/lib64/ruby/gems/1.8/gems/git-1.2.5/lib/git/base.rb:438:in`with_working'
        from /usr/lib64/ruby/gems/1.8/gems/git-1.2.5/lib/git/base.rb:437:in `chdir'
        from /usr/lib64/ruby/gems/1.8/gems/git-1.2.5/lib/git/base.rb:437:in`with_working'
        from /usr/lib64/ruby/gems/1.8/gems/TicGit-ng-1.0.2.12/lib/ticgit-ng/base.rb:395:in `in_branch'
        from /usr/lib64/ruby/gems/1.8/gems/git-1.2.5/lib/git/base.rb:391:in`with_index'
        from /usr/lib64/ruby/gems/1.8/gems/TicGit-ng-1.0.2.12/lib/ticgit-ng/base.rb:394:in `in_branch'
        from /usr/lib64/ruby/gems/1.8/gems/TicGit-ng-1.0.2.12/lib/ticgit-ng/ticket.rb:86:in`save_new'
        from /usr/lib64/ruby/gems/1.8/gems/TicGit-ng-1.0.2.12/lib/ticgit-ng/ticket.rb:32:in `create'
        from /usr/lib64/ruby/gems/1.8/gems/TicGit-ng-1.0.2.12/lib/ticgit-ng/base.rb:103:in`ticket_new'
        from /usr/lib64/ruby/gems/1.8/gems/TicGit-ng-1.0.2.12/lib/ticgit-ng/command/new.rb:32:in `execute'
        from /usr/lib64/ruby/gems/1.8/gems/TicGit-ng-1.0.2.12/lib/ticgit-ng/cli.rb:56:in`execute!'
        from /usr/lib64/ruby/gems/1.8/gems/TicGit-ng-1.0.2.12/lib/ticgit-ng/cli.rb:9:in `execute'
        from /usr/lib64/ruby/gems/1.8/gems/TicGit-ng-1.0.2.12/bin/ti:13
        from /usr/bin/ti:19:in`load'
        from /usr/bin/ti:19

I also tried through the web interface (ticgitweb) but got a backtrace too:

BACKTRACE
    /usr/lib64/ruby/gems/1.8/gems/sinatra-1.3.2/lib/sinatra/base.rb in write
        @env['rack.errors'].puts(msg)
    /usr/lib64/ruby/gems/1.8/gems/sinatra-1.3.2/lib/sinatra/base.rb in puts
        @env['rack.errors'].puts(msg)
    /usr/lib64/ruby/gems/1.8/gems/sinatra-1.3.2/lib/sinatra/base.rb in dump_errors!
        @env['rack.errors'].puts(msg)
    /usr/lib64/ruby/gems/1.8/gems/sinatra-1.3.2/lib/sinatra/base.rb in handle_exception!
        dump_errors! boom if settings.dump_errors?
    /usr/lib64/ruby/gems/1.8/gems/sinatra-1.3.2/lib/sinatra/base.rb in dispatch!
        handle_exception!(boom)
    /usr/lib64/ruby/gems/1.8/gems/sinatra-1.3.2/lib/sinatra/base.rb in call!
        invoke { dispatch! }
    /usr/lib64/ruby/gems/1.8/gems/sinatra-1.3.2/lib/sinatra/base.rb in invoke
        res = catch(:halt) { yield }
    /usr/lib64/ruby/gems/1.8/gems/sinatra-1.3.2/lib/sinatra/base.rb in catch
        res = catch(:halt) { yield }
    /usr/lib64/ruby/gems/1.8/gems/sinatra-1.3.2/lib/sinatra/base.rb in invoke
        res = catch(:halt) { yield }
    /usr/lib64/ruby/gems/1.8/gems/sinatra-1.3.2/lib/sinatra/base.rb in call!
        invoke { dispatch! }
    /usr/lib64/ruby/gems/1.8/gems/sinatra-1.3.2/lib/sinatra/base.rb in call
        dup.call!(env)
    /usr/lib64/ruby/gems/1.8/gems/rack-protection-1.2.0/lib/rack/protection/xss_header.rb in call
        status, headers, body = @app.call(env)
    /usr/lib64/ruby/gems/1.8/gems/rack-protection-1.2.0/lib/rack/protection/path_traversal.rb in call
        app.call env
    /usr/lib64/ruby/gems/1.8/gems/rack-protection-1.2.0/lib/rack/protection/json_csrf.rb in call
        status, headers, body = app.call(env)
    /usr/lib64/ruby/gems/1.8/gems/rack-protection-1.2.0/lib/rack/protection/base.rb in call
        result or app.call(env)
    /usr/lib64/ruby/gems/1.8/gems/rack-protection-1.2.0/lib/rack/protection/xss_header.rb in call
        status, headers, body = @app.call(env)
    /usr/lib64/ruby/gems/1.8/gems/rack-1.4.0/lib/rack/logger.rb in call
        @app.call(env)
    /usr/lib64/ruby/gems/1.8/gems/rack-1.4.0/lib/rack/head.rb in call
        status, headers, body = @app.call(env)
    /usr/lib64/ruby/gems/1.8/gems/rack-1.4.0/lib/rack/methodoverride.rb in call
        @app.call(env)
    /usr/lib64/ruby/gems/1.8/gems/sinatra-1.3.2/lib/sinatra/showexceptions.rb in call
        @app.call(env)
    /usr/lib64/ruby/gems/1.8/gems/sinatra-1.3.2/lib/sinatra/base.rb in call
        synchronize { prototype.call(env) }
    /usr/lib64/ruby/gems/1.8/gems/sinatra-1.3.2/lib/sinatra/base.rb in synchronize
        yield
    /usr/lib64/ruby/gems/1.8/gems/sinatra-1.3.2/lib/sinatra/base.rb in call
        synchronize { prototype.call(env) }
    /usr/lib64/ruby/gems/1.8/gems/rack-1.4.0/lib/rack/handler/webrick.rb in service
        status, headers, body = @app.call(env)
    /usr/lib64/ruby/1.8/webrick/httpserver.rb in service
        si.service(req, res)
    /usr/lib64/ruby/1.8/webrick/httpserver.rb in run
        server.service(req, res)
    /usr/lib64/ruby/1.8/webrick/server.rb in start_thread
        block ? block.call(sock) : run(sock)
    /usr/lib64/ruby/1.8/webrick/server.rb in start
        Thread.start{
    /usr/lib64/ruby/1.8/webrick/server.rb in start_thread
        Thread.start{
    /usr/lib64/ruby/1.8/webrick/server.rb in start
        th = start_thread(sock, &block)
    /usr/lib64/ruby/1.8/webrick/server.rb in each
        svrs[0].each{|svr|
    /usr/lib64/ruby/1.8/webrick/server.rb in start
        svrs[0].each{|svr|
    /usr/lib64/ruby/1.8/webrick/server.rb in start
        yield
    /usr/lib64/ruby/1.8/webrick/server.rb in start
        server_type.start{
    /usr/lib64/ruby/gems/1.8/gems/rack-1.4.0/lib/rack/handler/webrick.rb in run
        @server.start
    /usr/lib64/ruby/gems/1.8/gems/sinatra-1.3.2/lib/sinatra/base.rb in run!
        handler.run self, :Host => bind, :Port => port do |server|
    /usr/lib64/ruby/gems/1.8/gems/sinatra-1.3.2/lib/sinatra/main.rb in nil
        at_exit { Application.run! if $!.nil? && Application.run? }
    /usr/bin/ticgitweb in nil
        load Gem.bin_path('TicGit-ng', 'ticgitweb', version)

GET

No GET data.
POST
Variable    Value
comment
"New ticket comment."
tags
"crash"
title
"Simulation crash"
COOKIES

No cookie data.
Rack ENV
Variable    Value
CONTENT_LENGTH
583
CONTENT_TYPE
application/x-www-form-urlencoded
GATEWAY_INTERFACE
CGI/1.1
HTTP_ACCEPT
text/html,application/xhtml+xml,application/xml;q=0.9,_/_;q=0.8
HTTP_ACCEPT_CHARSET
ISO-8859-1,utf-8;q=0.7,*;q=0.7
HTTP_ACCEPT_ENCODING
gzip, deflate
HTTP_ACCEPT_LANGUAGE
en-us,en;q=0.5
HTTP_CONNECTION
keep-alive
HTTP_HOST
localhost:4567
HTTP_REFERER
http://localhost:4567/t/new
HTTP_USER_AGENT
Mozilla/5.0 (X11; Linux x86_64; rv:9.0.1) Gecko/20100101 Firefox/9.0.1
HTTP_VERSION
HTTP/1.1
PATH_INFO
/t/new
QUERY_STRING
REMOTE_ADDR
127.0.0.1
REMOTE_HOST
shockwave
REQUEST_METHOD
POST
REQUEST_PATH
/t/new
REQUEST_URI
http://localhost:4567/t/new
SCRIPT_NAME
SERVER_NAME
localhost
SERVER_PORT
4567
SERVER_PROTOCOL
HTTP/1.1
SERVER_SOFTWARE
WEBrick/1.3.1 (Ruby/1.8.7/2011-12-28)
rack.errors
# Object:0x7fa96d455358

rack.input
# StringIO:0x7fa96b674dc0

rack.logger
# <Logger:0x7fa96b66a0a0 @progname=nil, @logdev=#<Logger::LogDevice:0x7fa96b637b50 @shift_size=nil, @shift_age=nil, @dev=#<IO:0x7fa96ee0bab8>, @filename=nil, @mutex=#<Logger::LogDevice::LogDeviceMutex:0x7fa96b637b00 @mon_entering_queue=[], @mon_count=0, @mon_owner=nil, @mon_waiting_queue=[]>>, @level=1, @default_formatter=#<Logger::Formatter:0x7fa96b637ba0 @datetime_format=nil>, @formatter=nil>

rack.multiprocess
false
rack.multithread
true
rack.request.cookie_hash
{}
rack.request.form_hash
{"title"=>"Simulation on angel diverge", "comment"=>"Simulations on Angel (SHARNET) fail after some time.\r\n\r\nAn example is: 20120112_15h21_C01_Xe100nm_dt000.500as_nbions01415_SyesIyesEyesTnoRyes_potSymmetric_I8e12_WL98nm_FW100.0fs_Lrelaxed_A0.0_ALmd_b01.50_oclNvidia_ang23\r\n\r\nFrom time step 356881 (178.44018 fs) to 356901 (178.450012) the total potential energy goes from -2145.97 eV to 2.433e13 eV.\r\n\r\nLooking in Pymol, the cluster \"shakes\" and ion #740 seems to leave it.\r\n\r\nPossible bug in the lookup table access on a GPU?", "tags"=>"crash"}
rack.request.form_input
# StringIO:0x7fa96b674dc0

rack.request.form_vars
title=Simulation+on+angel+diverge&tags=crash&comment=Simulations+on+Angel+%28SHARNET%29+fail+after+some+time.%0D%0A%0D%0AAn+example+is%3A+20120112_15h21_C01_Xe100nm_dt000.500as_nbions01415_SyesIyesEyesTnoRyes_potSymmetric_I8e12_WL98nm_FW100.0fs_Lrelaxed_A0.0_ALmd_b01.50_oclNvidia_ang23%0D%0A%0D%0AFrom+time+step+356881+%28178.44018+fs%29+to+356901+%28178.450012%29+the+total+potential+energy+goes+from+-2145.97+eV+to+2.433e13+eV.%0D%0A%0D%0ALooking+in+Pymol%2C+the+cluster+%22shakes%22+and+ion+%23740+seems+to+leave+it.%0D%0A%0D%0APossible+bug+in+the+lookup+table+access+on+a+GPU%3F
rack.request.query_hash
{}
rack.request.query_string
rack.run_once
false
rack.url_scheme
http
rack.version
[1, 1]
sinatra.error
# <Errno::EIO: Input/output error>

**Comment by jeffWelling** [comment]
Hi, thanks for the feedback!
This looks like a bug that is related to a change that was made to the way debug output is printed. I'll see if I can reproduce this bug so that I can then squash it.
Cheers,
Jeff.

**Comment by fernandoflorez** [comment]
I'm able to reproduce this bug too. LMK if you i can provide data to test.

**Comment by wzph** [comment]
https://github.com/jeffWelling/ticgit/pull/46

**Comment by jeffWelling** [comment]
@wzph Thanks for the pull request! I've reviewed your code and everything looks in order, but I'm dealing with the theft of my laptop and so won't be able to apply the patch for another little while.
Please bear with me while I get back on my feet.
Thanks again for the patch!

**Comment by jeffWelling** [comment]
I've published TicGit-ng version 1.0.2.13 which, in my testing, resolves this bug. After someone else confirms this is resolved, the ticket will be closed.
Thanks to everyone for your time and feedback!

**Comment by nbigaouette** [comment]
Great! I just tried 1.0.2.14 and I can create a ticket just fine.

Thanks for your work!
