### ISSUE TITLE
bug on assign command

### ISSUE THREAD

**Issue by azimonti** [jeffWelling/ticgit#44]
Hello,
https://github.com/jeffWelling/ticgit/blob/deving/lib/ticgit-ng/command/assign.rb#L31
       elsif ARGV.length == 2 #ti assign {ticid}
          tic_id=ARGV[2]

shouldn't be
       elsif ARGV.length == 2 #ti assign {ticid}
          tic_id=ARGV[1]

:-)
Regards,
Marco

**Comment by jeffWelling** [comment]
Hi again!
Thanks for these, taking the time to file a bug for these means a lot to me. I'm in the middle of a move with another one coming up in some months, so I'm pressed for time lately, but I'll see what I can do about these issues that are piling up.

Your probably right about that line of code, but I need to do some testing to make sure that changing that line doesn't break some other behavior.  I've made small one-liner changes before that seemed trivial but that ended up breaking significant parts of the program elsewhere hehe.

Thanks again Marco!
Jeff

**Comment by jeffWelling** [comment]
Hi again Marco, I've just published version 1.0.2.14 which fixes this bug.
Thanks for filing it.
Cheers,
Jeff.
