### ISSUE TITLE
ti milestones not implemented?

### ISSUE THREAD

**Issue by azimonti** [jeffWelling/ticgit#45]
Hello,
I have the feeling the command "milestone" is not implemented.

https://github.com/jeffWelling/ticgit/blob/master/lib/ticgit-ng/command/milestone.rb

If I look at the code (also comparing with other commands), I can see a function

```
def parser(opts)
```

But (differently from other command) I did not found a function

```
def execute
```

which is pointing to the actual milestone implementation.
The command seems is not doing anything when I launch it.

Am I missing something?

thanks

**Comment by jeffWelling** [comment]
Hey again,  
Thanks for filing these bugs. It seems like there are a lot of these little unfinished stubs where the original author documented a behavior he/she hadn't actually written yet, or conversely didn't documented the behavior fully.  As I mentioned on the other issue, I'm pressed for time right now with other real world issues at the moment but I intend to rectify these as quickly as possible.

If your at all able and interested, I encourage you to download a copy of the source code and experimenting on your system to see if you can make heads or tails of these little nuisances.   

In either case, thank you for filing these bugs and I hope you'll look forward to the fix in a soon-to-be-released revision :)
Cheers,
Jeff.

**Comment by heoa** [comment]
Hello,
is this thread still an answer to this q [1]?

[1] http://stackoverflow.com/questions/11251480/how-to-use-milestones-in-ticgit

**Comment by jeffWelling** [comment]
Indeed it is! 
I'm sorry but I've been distracted by other things and haven't yet been able to implement it, but it is at the top of my list.

**Comment by jeffWelling** [comment]
Now that I've pushed out another release of TicGit-ng that has addressed a number of different bugs, I hope to be getting to writing the milestones portion of the code shortly, bear with me...

Duplicate (since been closed): https://github.com/jeffWelling/ticgit/issues/59
