### ISSUE TITLE
Odd ruby ERR dump with TAG: wrong number of parameters in Ubuntu

### ISSUE THREAD

**Issue by heoa** [jeffWelling/ticgit#50]
I followed the instructions here [1] for the installation on ubuntu.

[1] https://github.com/jeffWelling/ticgit

ERR -dump

$ ti tag 
You need to at least specify one tag to add

/var/lib/gems/1.8/gems/TicGit-ng-1.0.2.14/lib/ticgit-ng/command/tag.rb:26:in `parser': wrong number of arguments (0 for 1) (ArgumentError)
    from /var/lib/gems/1.8/gems/TicGit-ng-1.0.2.14/lib/ticgit-ng/command/tag.rb:26:in`execute'
    from /var/lib/gems/1.8/gems/TicGit-ng-1.0.2.14/lib/ticgit-ng/cli.rb:56:in `execute!'
    from /var/lib/gems/1.8/gems/TicGit-ng-1.0.2.14/lib/ticgit-ng/cli.rb:9:in`execute'
    from /var/lib/gems/1.8/gems/TicGit-ng-1.0.2.14/bin/ti:13
    from /usr/local/bin/ti:19:in `load'
    from /usr/local/bin/ti:19

**Comment by jeffWelling** [comment]
Hi, and thanks for taking the time to file this bug!

This appears to be a combination of a number of problems.  1) insufficient and or incomplete documentation, 2) a core dump is presented which draws attention away from the more helpful error message, 3) a misunderstanding of how to use ticgit (probably as a consequence of 1).

Step one for using `ti tag` is to make sure that you have a ticket 'checked out'.  Use `ti list` and look for a ticket with a `*` in the far left column.  If you don't see a `*` then you may not have a ticket checked out yet. If not, check out a ticket.

Step two is to do `ti tag fubar` to add for example the tag 'fubar' to the currently checked-out ticket.  This will not produce any output.

Step three (optional) use `ti list` to show the list of tickets with your new tag.

I apologize for the confusion around this, to resolve this problem I will be 1) fixing the documentation related to the tag command as well as TicGit-ng in general, 2) I will work to make sure that when a problem is encountered in using TicGit-ng that it produces helpful output and does not present a core dump, and 3) I will leave this ticket open until the documentation and core dump problems are resolved as a reminder to myself to fix these issues.

Do the steps listed above clear up any confusion about how to use `ti tag`? If not, please post back and we'll work to get this cleared up.  Thanks again for the feedback!

**Comment by jeffWelling** [comment]
This has been addressed in the latest version of TicGit-ng.  Improper usage of the tag command now results in a printout of the help page and a graceful fail and no longer produces a stack trace.

Please update to the latest version and let me know if you are still having this problem, in the meantime I will close this issue.
