### ISSUE TITLE
$ ti attach -- ERR DUMP in Ubuntu

### ISSUE THREAD

**Issue by heoa** [jeffWelling/ticgit#54]
$ ti attach
/var/lib/gems/1.8/gems/TicGit-ng-1.0.2.14/lib/ticgit-ng/command.rb:29:in `const_get': no such file to load -- ticgit-ng/command/attach (LoadError)
    from /var/lib/gems/1.8/gems/TicGit-ng-1.0.2.14/lib/ticgit-ng/command.rb:29:in`get'
    from /var/lib/gems/1.8/gems/TicGit-ng-1.0.2.14/lib/ticgit-ng/cli.rb:45:in `execute!'
    from /var/lib/gems/1.8/gems/TicGit-ng-1.0.2.14/lib/ticgit-ng/cli.rb:9:in`execute'
    from /var/lib/gems/1.8/gems/TicGit-ng-1.0.2.14/bin/ti:13
    from /usr/local/bin/ti:19:in `load'
    from /usr/local/bin/ti:19

**Comment by jeffWelling** [comment]
Closed as duplicate of issue #63
