### ISSUE TITLE
Separate GUI and commandline aka CLI

### ISSUE THREAD

**Issue by heoa** [jeffWelling/ticgit#55]
I am puzzled how they are managed. I would kill all ticgitweb --things for now, there is too many bugs with ticgit!

I. ticgit ---  PRIORITY ONE
II. ticgitweb --- some sinatra -hack  (I think this should be anyway rewritten with something like CouchDB, forget)

It is relatively easy to fix the bugs such as [1] when we get the I working! Do not waste time with [1], please.

[1] https://github.com/jeffWelling/ticgit/issues/48#issuecomment-6640816

**Comment by jeffWelling** [comment]
I welcome any and all contributions you would care to make, including a rewrite of ticgitweb and or fixing the bugs themselves.  I don't have unlimited time and have other commitments to attend to but I will certainly do my best with the time that I have, and I do appreciate all feedback including the filing of bugs and expressing of opinions! Thank You!

**Comment by heoa** [comment]
Moved the key observation here [1], Ticgit 2008/2009 version seems to lack the features most of which are currently broken or not really needed. I think the best way is to use Ticgit and then create some graphical thing to manage milestones/priorities without third-party content-hosts (dependencies) such as Bitbucket.org or Github.com.

[1] https://github.com/jeffWelling/ticgit/issues/64
