### ISSUE TITLE
Make consistency over different Git -projects: Gitolite + Ticgit = ?

### ISSUE THREAD

**Issue by heoa** [jeffWelling/ticgit#56]
Gitolite [1] is a freaking cool software. Ticgit [2] looks promising sofware. Gource [3] looks promising. 

Now I feel it is extremely important that we create some sort of consistency with the design. Permissions and tickets usually belong to manager -level guy or some central guy.

**Related projects**
[1] https://github.com/sitaramc/gitolite/
[2] https://github.com/jeffWelling/ticgit
[3] http://code.google.com/p/gource/

**Related Tickets**
[4] https://github.com/jeffWelling/ticgit/issues/52

**Comment by jeffWelling** [comment]
Wow, thanks for pointing this out.  I wasn't aware how many other players had entered the field, but where-ever possible interoperability should be emphasized and we should learn from each other where possible! I'll definitely check these out for additional ideas.
