### ISSUE TITLE
Centrally Managed Tickets-Perms -UI/repo for Manager/Producer/Leader

### ISSUE THREAD

**Issue by heoa** [jeffWelling/ticgit#58]
[1] https://github.com/jeffWelling/ticgit/issues/57

**Comment by heoa** [comment]
I want to make this milestone, how?

**Comment by jeffWelling** [comment]
I don't know, I don't really use milestones in Github Issues...

**Comment by heoa** [comment]
I can see it :p

Bugs are shallow when you kill the clutter!
1. Outline: tickets/milestone/etc
2. think
3. attack
4. re-consider(tickets/milestones/etc) and study
5. attack
6. re-check and study
7. back to 1

**Comment by jeffWelling** [comment]
Im not sure what that last comment is supposed to be, is that how you attack tickets, or how you think I should attack tickets?

**Comment by heoa** [comment]
I cannot make head or tail about tickets in Github, they suck. Github sucks with tickets. It is extremely hard to see the most urgent thing to do. Now I feel the most urgent thing to do is to decide a milestone such as [1]. Then think and investigate:

**CLI (high priority)**
I. structure of things under version-control and what the heck is the maven here [2], clutter?
II. independent content-hosting -q here [3]
III. could we co-operate with other projects? Please, notice the Bremner.
IV. ??
V. still investigating [4]

**GUI (low priority)**
1. Github -style things [5]
2. Probably replacing the Sinatra with CouchDB, still thinking...

**References**
[1] https://github.com/jeffWelling/ticgit/issues/57
[2] http://stackoverflow.com/questions/11253615/structure-of-projects-in-version-control-something-like-maven-for-non-java-pro
[3] http://stackoverflow.com/a/11007681/164148
[4] http://stackoverflow.com/questions/11218069/version-control-for-tickets
[5] http://stackoverflow.com/questions/11251941/how-can-i-see-github-style-things-such-as-punchcards-and-timeline-of-git-repo

**Comment by heoa** [comment]
I don't fork your repo because I am uncertain of the direction of this project. I would like to know more about your priorities. If we can decide the basic concepts conceptually, then it is easier to co-operate -- certain milestones are must so we can objectively evaluate our work!

**Milestones -suggestions**
0. simple CLI -ticgit -rewrite compatible with Gitolite
1. central perms and ticket UI
2. ticgit Bitbucket -style-clone-UI
3. Github -style-graphical-bells-and-whistles-analysis-tool
4. ...

**Tickets**
0. design Ticgit extensible with other Git -projects (investigate...)
0.1. design of Ticgit compatible with Gitolite [6]

[6] https://github.com/jeffWelling/ticgit/issues/56

**Comment by jeffWelling** [comment]
Why would _my_ priorities matter for _your_ fork?  If you fork my project, you can have _your own_ priorities, ordered however you like.  The combined effort would mean that we both accomplish the tasks we want as we've prioritized them respectively.  I work on X, you work on Y, and when we're done, we have both X and Y finished even though we each only worked on one or the other.

I evaluate my work based on a "Does the feature I'm implementing do what I want yet?"  ?  "Feature is done, move to next feature" : "Feature not complete, continue working on feature"; methodology.

If a complete rewrite of ticgit is required for gitolite compatibility, I'm afraid it simply won't be happening any time soon by my hand, but perhaps I misunderstood what you meant there.  
I only have an hour here or there to tinker and improve this, spending a whopping amount of time in the design phase for something I spend so little time on seems counter productive from my position.  But if you want to make a change pursuant to your own design methodology I will be happy to do my best to integrate your change and publish said changes in the TicGit-ng gem.  

The general momentum of the project from my perspective is merely geared towards being as usable as possible for as many people as possible while implementing the features people expect from a bug tracker, that's as much direction as I've needed so far. IMO the project doesn't need more planning, it needs more man-hours of work put into it.
