### ISSUE TITLE
Clean up the forks, why so many dummy forks?

### ISSUE THREAD

**Issue by heoa** [jeffWelling/ticgit#60]
I would like to know why you have created so many dummy forks? I personally create them by accident when I manage repos over many computers but they are really bad... I don't know how but I would like to kill the unnecessary forks by you there [1], it is hard to find the genuine forks that are really under development. I am investigating whether someone is developing now something from this code or the best option complete rewrite or something else?

[1] https://github.com/jeffWelling/ticgit/network

**Comment by xiongchiamiov** [comment]
Forks aren't created by Jeff, they're created by other users (hence, fork); he can do nothing about them.

**Comment by jeffWelling** [comment]
Well I _could_ merge them -- I didn't realize the number had risen since I'd last checked. 

Also, I'm wondering if he meant to use the word 'tags' or 'branches' instead of the word 'fork'...

**Comment by jeffWelling** [comment]
Isn't it kind of easy to tell which forks are genuinely still being developed by the number of commits on the timeline? I mean, if it's a one-off commit then they probably only wanted to change one thing, not take on the whole project.  My brief scan of the network you linked shows that I'm the only one actively maintaining TicGit, though the phrase 'actively maintaining' is being rather generous at the moment...

**Comment by heoa** [comment]
Well check the Blue -arrows there[1], Jeff is Black and Blue. My friend once suggested me to use "$ git pull -r" in similar situation to fix similar problem where I was programming in multiple machines -- I cannot now rememeber how to fix it but it was something like that, one needs to manually check things. Anyway what is the reason for Blue and Black there [1] for one user? It over-rates the fork -numbers etc.

Yes, "$ git pull --rebase" is apparently the solution. There is some flag not to do things (anyway -vr -flag-for-checking should handle this), let me know whether you find the combo faster to clean up the forks...

```
   --rebase
       Rebase the current branch on top of the upstream branch after fetching. If there is a remote-tracking branch corresponding to
       the upstream branch and the upstream branch was rebased since last fetched, the rebase uses that information to avoid rebasing
       non-local changes.

       See pull.rebase, branch.<name>.rebase and branch.autosetuprebase in git-config(1) if you want to make git pull always use
       --rebase instead of merging.

           Note
           This is a potentially dangerous mode of operation. It rewrites history, which does not bode well when you published that
           history already. Do not use this option unless you have read git-rebase(1) carefully.
```

[1] http://koti.kapsi.fi/~he/blues_jeff.png

**Comment by xiongchiamiov** [comment]
One person programming a single project on multiple machines is a different thing; this is a number of _other_ people making _their own_ changes that may or may not be beneficial for the upstream.

**Comment by heoa** [comment]
If you have better ideas, feel free to suggest a git -solution to clean the forks from one user. I think Jeff can fix the Blue/Black arrows simply by adding the flag "-r" for his pulls. Or am I misunderstanding something?

**Comment by xiongchiamiov** [comment]
Oh, ok, now I see what you mean.

Yes, if he rebased branches instead of merging them, that wouldn't appear.  Doing a `merge --no-ff` is helpful, though, in keeping a record of what happened - we use a similar scheme at work.  However, if he deletes the hotfix branches that have been merged in, it'll clean things up a bit.

@jeffWelling you may want to look at [git-sweep](https://github.com/arc90/git-sweep).

**Comment by jeffWelling** [comment]
Thats exactly why its the way it is, no loss of information. I intentionally use --no-ff instead of a base merge to get that. I could clean up some of the hotfixes that are known to work though, that would clean it up.

**Comment by jeffWelling** [comment]
This is the branching model Im following http://nvie.com/posts/a-successful-git-branching-model/

**Comment by heoa** [comment]
@jeffWelling Thank you for the informative material!

Do you follow the rule below with release -branches?

> "every commit on master is a new release by definition, remember"

I wish to find your release branches, some easy to get them?

**Comment by jeffWelling** [comment]
Lately yes that's a rule I've been trying to follow, no development work should ever be done on master IMO.

**Comment by heoa** [comment]
@jeffWelling Suppose I want to make a hotfix, how do I get a hotfix -number allocated? 

I would like fix things here and there. One thing is trivial thing with ticgitweb, can you assist how to proceed not to mess things? Is it so that I fork in Github and then you handle the hotfix -numbers so I don't need to worry about them?

**Comment by jeffWelling** [comment]
I try to handle the hotfix numbering myself, I try to vaguely follow this: https://github.com/jeffWelling/ticgit/wiki/Releases

It's available up on the wiki, though judging from how long it took me to find it, the wiki needs a redesign itself lol
