### ISSUE TITLE
"$ git init; ti init; ti" firing bugs with any command, no error-handling with null -repo

### ISSUE THREAD

**Issue by heoa** [jeffWelling/ticgit#62]
Tested on 12.04 Ubuntu. It seems to lack error handling with Null -repo.

$ cat /proc/version
Linux version 3.2.0-26-generic (buildd@batsu) (gcc version 4.6.3 (Ubuntu/Linaro 4.6.3-1ubuntu5) ) #41-Ubuntu SMP Thu Jun 14 17:49:24 UTC 2012

$ ti new -t 'testing1'
/var/lib/gems/1.8/gems/git-1.2.5/lib/git/lib.rb:700:in `command': git branch "-a"  2>&1:fatal: Failed to resolve HEAD as a valid ref. (Git::GitExecuteError)
    from /var/lib/gems/1.8/gems/git-1.2.5/lib/git/lib.rb:672:in`command_lines'
    from /var/lib/gems/1.8/gems/git-1.2.5/lib/git/lib.rb:200:in `branches_all'
    from /var/lib/gems/1.8/gems/git-1.2.5/lib/git/branches.rb:12:in`initialize'
    from /var/lib/gems/1.8/gems/git-1.2.5/lib/git/base.rb:180:in `new'
    from /var/lib/gems/1.8/gems/git-1.2.5/lib/git/base.rb:180:in`branches'
    from /var/lib/gems/1.8/gems/TicGit-ng-1.0.2.14/lib/ticgit-ng/base.rb:414:in `which_branch?'
    from /var/lib/gems/1.8/gems/TicGit-ng-1.0.2.14/lib/ticgit-ng/base.rb:32:in`initialize'
    from /var/lib/gems/1.8/gems/TicGit-ng-1.0.2.14/lib/ticgit-ng.rb:50:in `new'
    from /var/lib/gems/1.8/gems/TicGit-ng-1.0.2.14/lib/ticgit-ng.rb:50:in`open'
    from /var/lib/gems/1.8/gems/TicGit-ng-1.0.2.14/lib/ticgit-ng/cli.rb:34:in `initialize'
    from /var/lib/gems/1.8/gems/TicGit-ng-1.0.2.14/lib/ticgit-ng/cli.rb:14:in`new'
    from /var/lib/gems/1.8/gems/TicGit-ng-1.0.2.14/lib/ticgit-ng/cli.rb:14:in `parse'
    from /var/lib/gems/1.8/gems/TicGit-ng-1.0.2.14/lib/ticgit-ng/cli.rb:9:in`execute'
    from /var/lib/gems/1.8/gems/TicGit-ng-1.0.2.14/bin/ti:13
    from /usr/local/bin/ti:19:in `load'
    from /usr/local/bin/ti:19
xyz@xyz:~/T$ ti new --help
/var/lib/gems/1.8/gems/git-1.2.5/lib/git/lib.rb:700:in`command': git branch "-a"  2>&1:fatal: Failed to resolve HEAD as a valid ref. (Git::GitExecuteError)
    from /var/lib/gems/1.8/gems/git-1.2.5/lib/git/lib.rb:672:in `command_lines'
    from /var/lib/gems/1.8/gems/git-1.2.5/lib/git/lib.rb:200:in`branches_all'
    from /var/lib/gems/1.8/gems/git-1.2.5/lib/git/branches.rb:12:in `initialize'
    from /var/lib/gems/1.8/gems/git-1.2.5/lib/git/base.rb:180:in`new'
    from /var/lib/gems/1.8/gems/git-1.2.5/lib/git/base.rb:180:in `branches'
    from /var/lib/gems/1.8/gems/TicGit-ng-1.0.2.14/lib/ticgit-ng/base.rb:414:in`which_branch?'
    from /var/lib/gems/1.8/gems/TicGit-ng-1.0.2.14/lib/ticgit-ng/base.rb:32:in `initialize'
    from /var/lib/gems/1.8/gems/TicGit-ng-1.0.2.14/lib/ticgit-ng.rb:50:in`new'
    from /var/lib/gems/1.8/gems/TicGit-ng-1.0.2.14/lib/ticgit-ng.rb:50:in `open'
    from /var/lib/gems/1.8/gems/TicGit-ng-1.0.2.14/lib/ticgit-ng/cli.rb:34:in`initialize'
    from /var/lib/gems/1.8/gems/TicGit-ng-1.0.2.14/lib/ticgit-ng/cli.rb:14:in `new'
    from /var/lib/gems/1.8/gems/TicGit-ng-1.0.2.14/lib/ticgit-ng/cli.rb:14:in`parse'
    from /var/lib/gems/1.8/gems/TicGit-ng-1.0.2.14/lib/ticgit-ng/cli.rb:9:in `execute'
    from /var/lib/gems/1.8/gems/TicGit-ng-1.0.2.14/bin/ti:13
    from /usr/local/bin/ti:19:in`load'
    from /usr/local/bin/ti:19
xyz@xyz:~/T$ ti --help
/var/lib/gems/1.8/gems/git-1.2.5/lib/git/lib.rb:700:in `command': git branch "-a"  2>&1:fatal: Failed to resolve HEAD as a valid ref. (Git::GitExecuteError)
    from /var/lib/gems/1.8/gems/git-1.2.5/lib/git/lib.rb:672:in`command_lines'
    from /var/lib/gems/1.8/gems/git-1.2.5/lib/git/lib.rb:200:in `branches_all'
    from /var/lib/gems/1.8/gems/git-1.2.5/lib/git/branches.rb:12:in`initialize'
    from /var/lib/gems/1.8/gems/git-1.2.5/lib/git/base.rb:180:in `new'
    from /var/lib/gems/1.8/gems/git-1.2.5/lib/git/base.rb:180:in`branches'
    from /var/lib/gems/1.8/gems/TicGit-ng-1.0.2.14/lib/ticgit-ng/base.rb:414:in `which_branch?'
    from /var/lib/gems/1.8/gems/TicGit-ng-1.0.2.14/lib/ticgit-ng/base.rb:32:in`initialize'
    from /var/lib/gems/1.8/gems/TicGit-ng-1.0.2.14/lib/ticgit-ng.rb:50:in `new'
    from /var/lib/gems/1.8/gems/TicGit-ng-1.0.2.14/lib/ticgit-ng.rb:50:in`open'
    from /var/lib/gems/1.8/gems/TicGit-ng-1.0.2.14/lib/ticgit-ng/cli.rb:34:in `initialize'
    from /var/lib/gems/1.8/gems/TicGit-ng-1.0.2.14/lib/ticgit-ng/cli.rb:14:in`new'
    from /var/lib/gems/1.8/gems/TicGit-ng-1.0.2.14/lib/ticgit-ng/cli.rb:14:in `parse'
    from /var/lib/gems/1.8/gems/TicGit-ng-1.0.2.14/lib/ticgit-ng/cli.rb:9:in`execute'
    from /var/lib/gems/1.8/gems/TicGit-ng-1.0.2.14/bin/ti:13
    from /usr/local/bin/ti:19:in `load'
    from /usr/local/bin/ti:19
xyz@xyz:~/T$ ti --help
/var/lib/gems/1.8/gems/git-1.2.5/lib/git/lib.rb:700:in`command': git branch "-a"  2>&1:fatal: Failed to resolve HEAD as a valid ref. (Git::GitExecuteError)
    from /var/lib/gems/1.8/gems/git-1.2.5/lib/git/lib.rb:672:in `command_lines'
    from /var/lib/gems/1.8/gems/git-1.2.5/lib/git/lib.rb:200:in`branches_all'
    from /var/lib/gems/1.8/gems/git-1.2.5/lib/git/branches.rb:12:in `initialize'
    from /var/lib/gems/1.8/gems/git-1.2.5/lib/git/base.rb:180:in`new'
    from /var/lib/gems/1.8/gems/git-1.2.5/lib/git/base.rb:180:in `branches'
    from /var/lib/gems/1.8/gems/TicGit-ng-1.0.2.14/lib/ticgit-ng/base.rb:414:in`which_branch?'
    from /var/lib/gems/1.8/gems/TicGit-ng-1.0.2.14/lib/ticgit-ng/base.rb:32:in `initialize'
    from /var/lib/gems/1.8/gems/TicGit-ng-1.0.2.14/lib/ticgit-ng.rb:50:in`new'
    from /var/lib/gems/1.8/gems/TicGit-ng-1.0.2.14/lib/ticgit-ng.rb:50:in `open'
    from /var/lib/gems/1.8/gems/TicGit-ng-1.0.2.14/lib/ticgit-ng/cli.rb:34:in`initialize'
    from /var/lib/gems/1.8/gems/TicGit-ng-1.0.2.14/lib/ticgit-ng/cli.rb:14:in `new'
    from /var/lib/gems/1.8/gems/TicGit-ng-1.0.2.14/lib/ticgit-ng/cli.rb:14:in`parse'
    from /var/lib/gems/1.8/gems/TicGit-ng-1.0.2.14/lib/ticgit-ng/cli.rb:9:in `execute'
    from /var/lib/gems/1.8/gems/TicGit-ng-1.0.2.14/bin/ti:13
    from /usr/local/bin/ti:19:in`load'
    from /usr/local/bin/ti:19
xyz@xyz:~/T$ ti
/var/lib/gems/1.8/gems/git-1.2.5/lib/git/lib.rb:700:in `command': git branch "-a"  2>&1:fatal: Failed to resolve HEAD as a valid ref. (Git::GitExecuteError)
    from /var/lib/gems/1.8/gems/git-1.2.5/lib/git/lib.rb:672:in`command_lines'
    from /var/lib/gems/1.8/gems/git-1.2.5/lib/git/lib.rb:200:in `branches_all'
    from /var/lib/gems/1.8/gems/git-1.2.5/lib/git/branches.rb:12:in`initialize'
    from /var/lib/gems/1.8/gems/git-1.2.5/lib/git/base.rb:180:in `new'
    from /var/lib/gems/1.8/gems/git-1.2.5/lib/git/base.rb:180:in`branches'
    from /var/lib/gems/1.8/gems/TicGit-ng-1.0.2.14/lib/ticgit-ng/base.rb:414:in `which_branch?'
    from /var/lib/gems/1.8/gems/TicGit-ng-1.0.2.14/lib/ticgit-ng/base.rb:32:in`initialize'
    from /var/lib/gems/1.8/gems/TicGit-ng-1.0.2.14/lib/ticgit-ng.rb:50:in `new'
    from /var/lib/gems/1.8/gems/TicGit-ng-1.0.2.14/lib/ticgit-ng.rb:50:in`open'
    from /var/lib/gems/1.8/gems/TicGit-ng-1.0.2.14/lib/ticgit-ng/cli.rb:34:in `initialize'
    from /var/lib/gems/1.8/gems/TicGit-ng-1.0.2.14/lib/ticgit-ng/cli.rb:14:in`new'
    from /var/lib/gems/1.8/gems/TicGit-ng-1.0.2.14/lib/ticgit-ng/cli.rb:14:in `parse'
    from /var/lib/gems/1.8/gems/TicGit-ng-1.0.2.14/lib/ticgit-ng/cli.rb:9:in`execute'
    from /var/lib/gems/1.8/gems/TicGit-ng-1.0.2.14/bin/ti:13
    from /usr/local/bin/ti:19:in `load'
    from /usr/local/bin/ti:19

**Comment by jeffWelling** [comment]
This has been dealt with in the latest version, though it does seem like an edge case.  Please update your gem and check that this issue is resolved for you.

The issue that I fixed for this (it wasn't 100% clear to me what your problem was) was that TicGit-ng didn't check for and gracefully fail when someone tried to use TicGit-ng with a repository that did not have any commits in it yet. To resolve this, I added error checking for this condition and an rspec spec to prevent regression, so if I understood your problem correctly then hopefully this is resolved.

Let me know, in the meantime I will mark this issue as closed.

**Comment by heoa** [comment]
I am using now Debian and some errors, not sure whether I am running the newest ticgit.

$ cat /proc/version 
Linux version 3.2.0-0.bpo.2-686-pae (Debian 3.2.20-1~bpo60+1) (debian-kernel@lists.debian.org) (gcc version 4.4.5 (Debian 4.4.5-8) ) #1 SMP Sat Jun 30 08:29:17 UTC 2012
$ git init
$ ti init
/usr/lib/ruby/1.8/git/lib.rb:643:in `command': git branch -a 2>&1:fatal: Failed to resolve HEAD as a valid ref. (Git::GitExecuteError)
    from /usr/lib/ruby/1.8/git/lib.rb:615:in`command_lines'
    from /usr/lib/ruby/1.8/git/lib.rb:209:in `branches_all'
    from /usr/lib/ruby/1.8/ticgit/base.rb:241:in`load_tickets'
    from /usr/lib/ruby/1.8/ticgit/base.rb:72:in `reset_ticgit'
    from /usr/lib/ruby/1.8/ticgit/base.rb:38:in`initialize'
    from /usr/lib/ruby/1.8/ticgit.rb:25:in `new'
    from /usr/lib/ruby/1.8/ticgit.rb:25:in`open'
    from /usr/lib/ruby/1.8/ticgit/cli.rb:23:in `initialize'
    from /usr/lib/ruby/1.8/ticgit/cli.rb:16:in`new'
    from /usr/lib/ruby/1.8/ticgit/cli.rb:16:in `parse'
    from /usr/lib/ruby/1.8/ticgit/cli.rb:12:in`execute'
    from /usr/bin/ti:10
$ ti
/usr/lib/ruby/1.8/git/lib.rb:643:in `command': git branch -a 2>&1:fatal: Failed to resolve HEAD as a valid ref. (Git::GitExecuteError)
    from /usr/lib/ruby/1.8/git/lib.rb:615:in`command_lines'
    from /usr/lib/ruby/1.8/git/lib.rb:209:in `branches_all'
    from /usr/lib/ruby/1.8/ticgit/base.rb:241:in`load_tickets'
    from /usr/lib/ruby/1.8/ticgit/base.rb:72:in `reset_ticgit'
    from /usr/lib/ruby/1.8/ticgit/base.rb:38:in`initialize'
    from /usr/lib/ruby/1.8/ticgit.rb:25:in `new'
    from /usr/lib/ruby/1.8/ticgit.rb:25:in`open'
    from /usr/lib/ruby/1.8/ticgit/cli.rb:23:in `initialize'
    from /usr/lib/ruby/1.8/ticgit/cli.rb:16:in`new'
    from /usr/lib/ruby/1.8/ticgit/cli.rb:16:in `parse'
    from /usr/lib/ruby/1.8/ticgit/cli.rb:12:in`execute'
    from /usr/bin/ti:10
$ dpkg -l ticgit
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                       Version                    Description
+++-==========================-==========================-====================================================================
ii  ticgit                     0.3.3-2                    ticketing system built on Git

**Comment by jeffWelling** [comment]
1) That's improper usage for TicGit-ng. The appropriate usage is to first add at least one commit to git, and in the latest version of TicGit-ng there has been code added to make sure that when you try to use TicGit-ng without adding commits to  git first that TicGit-ng fails gracefully and explains why it has failed.

2) It appears you are using TicGit, not TicGit-ng, and should be filing these issues on the TicGit page instead of the TicGit-ng Issues page.
