### ISSUE TITLE
Rollback to Ticgit 2008/2009 -version?

### ISSUE THREAD

**Issue by heoa** [jeffWelling/ticgit#64]
Properties added in Ticgit-ng seems to be more or less broken or clutter i.e. not really needed. I have tested now some version from 2008/2009 (my admin probably installed [5]) and you can see below the difference -- sorry I cannot see now 'version' -command with the software arg...

MY CURRENT IDEA that may change is keep 2008/2009-style-focused approach and move things such as Points(priority) and milestones elsewhere, to some GUI -- not to jam everything to Ticgit. I feel features such as sync/attach are reinventing-the-wheel so I am suggesting to remove them, cannot undersntand them and anyway they are firing bugs.

Unless someone has some reason to continue ticgit-ng development, I at least need to go back to version [5] that at least seems to fire less errors (although I have already got some errors, anyway investigating, not yet decided).

2008 Ticgit -version
        assign
        checkout
        comment
        list
        new
        show
        state
        tag
Ticgit-ng
        assign
        checkout
        comment
        list
        new
        show
        state
        tag
        MOST OF THEM BROKEN or clutter
                attach          ?? [2] errs, kill this [1].
                init                ?? 
                milestone   ?? NOT WORKING.
                points          ?? 
                recent          ?? ti list |sort -k2
                sync            ?? [1] and then "git push ticgit"??

2008 version seesm to be more robust to Ticgit-ng, version so suggesting to switch back...
1. Do we really need attach/sync/init/recent? 
2. Do we really need milestones/points?

SUGGESTION: go back to Ticgit (without the broken 'features') and move milestones/points [4] to GUI [3].
1. How can we work with Ticgit/Gitolite/Coming-GUI(with points/milestones)?

[1] https://github.com/jeffWelling/ticgit/issues/57#issuecomment-6689562
[2] https://github.com/jeffWelling/ticgit/issues/63
[3] https://github.com/jeffWelling/ticgit/issues/57
[4] BitBucket.org has some good ideas
[5] https://github.com/manveru/ticgit

**Comment by heoa** [comment]
More my reasoning here [1]. Now the challenge is to integrate or make things somehow easier to use with different things such as :
1. git
2. ticgit
3. gitk
4. gitolite
5. ...?

Perhaps some graphical thing [2] and set up some easy content-host for things, not sure yet, thinking. Current content-hosts seem to be reluctant to create features that would help developers to move tickets elsewhere easily. If we are going to stick with them, they need to co-operate or we need to find other ways, perhaps forgetting them totally.

[1] https://github.com/jeffWelling/ticgit/issues/57#issuecomment-6695317
[2] https://github.com/jeffWelling/ticgit/issues/56

**Comment by jeffWelling** [comment]
Since the versioning system will be staying the way it is for the time being I shall close this issue.  If there are other things you would like to continue discussion on I advise you to open a new ticket or continue said discussion on the appropriate ticket.
