### ISSUE TITLE
Creating a ticket with comments and tags

### ISSUE THREAD

**Issue by shmul** [jeffWelling/ticgit#68]
Hi,

How can I create a ticket and add a description/comment to it, tags and possibly even assign it in a single operation?

Cheers,
Shmul

**Comment by jeffWelling** [comment]
To create a ticket, do `ti new`. The first line will become the title of the ticket, and any lines between that and the commented-out message at the bottom will become the first comment on the ticket.  To add tags, use the 'tags:' line at the bottom, add your tags delimited by commas.

At present there is no way to create a new ticket and assign it to someone within the same operation, but that will be a feature in coming versions.

**Comment by shmul** [comment]
Hi,

Thanks for the reply. I thought it would be nice to be able to fill in all the data in a single operation, which is especially useful if you have an existing list of tickets you want to import into ticgit-ng. This for example can be done by adding some pre-defined markup that tells where the comment starts and where the tags are. Below is a silly little implementation for this. It works for me on some trivial examples like:
    ti new -t "hello cruel world comment: a comment tags: tag 2, tag 5"

Oddly, while `ti list` command will show the newly created tags, the call to `ticket_show` that concludes the new ticket creation does not.

Cheers,
Shmul

```
--- new.orig    2012-07-15 14:10:02.000000000 +0300
+++ new.rb  2012-07-16 08:51:27.000000000 +0300
@@ -10,7 +10,11 @@

       def execute
         if title = options.title
-          ticket_show(tic.ticket_new(title, options.to_hash))
+          matches = /^(.+?)(comment: .*?)?(tags: .*)?$/.match(title)
+          ticket = tic.ticket_new(matches[1], options.to_hash)
+          ticket.add_comment(matches[2][/^comment: (.+)/,1]) if matches[2]
+          ticket.add_tag(matches[3][/^tags: (.+)/,1]) if matches[3]
+          ticket_show(ticket)
         else
           # interactive
           prompt = "\n# ---\ntags:\n"
```

**Comment by shmul** [comment]
Here is an updated patch with a bug fix and support for `assign` as well . Not the cleanest piece of code, but it makes the point (I hope).

```
--- new.orig    2012-07-15 14:10:02.000000000 +0300
+++ new.rb  2012-07-16 12:34:38.000000000 +0300
@@ -10,7 +10,12 @@

       def execute
         if title = options.title
-          ticket_show(tic.ticket_new(title, options.to_hash))
+          matches = /^(.+?)(comment: .*?)?(tags: .*?)?(assign: .*?)?$/.match(title)
+          ticket = tic.ticket_new(matches[1], options.to_hash)
+          ticket.add_comment(matches[2][/^comment: (.+)/,1]) if matches[2]
+          ticket.add_tag(matches[3][/^tags: (.+)/,1]) if matches[3]
+          ticket.change_assigned(matches[4][/^assign: (.+)/,1]) if matches[4]
+          ticket_show(ticket)
         else
           # interactive
           prompt = "\n# ---\ntags:\n"
```

Cheers,
Shmul

**Comment by jeffWelling** [comment]
Thanks, this will come in handy when I start looking at fixing all the little inconsistencies such as the problem you pointed out regarding ticket_show.
Thanks for the feedback!
