### ISSUE TITLE
tagging only works on checked out issue

### ISSUE THREAD

**Issue by holtzermann17** [jeffWelling/ticgit#70]
`ti checkout TIC_ID && ti tag TAG_NAME`
works, but
`ti tag TIC_ID TAG_NAME`
does not work.

**Comment by jeffWelling** [comment]
Thank you for filing this, I will address it with the release I am currently working on.

**Comment by jeffWelling** [comment]
I believe this is fixed in the latest version of TicGit-ng, can you please do an update of your gems and double check that this problem is resolved for you?
