### ISSUE TITLE
ticgit is not path independent

### ISSUE THREAD

**Issue by holtzermann17** [jeffWelling/ticgit#71]
I find it a bit strange that ticgit doesn't actually store all of its config information within the repo itself.

Example:

`~/ftg $ ti list`

... works as expected.

```
~/ftg $ cd ..
~ $ mv ftg ftg.git
~ $ cd ftg.git
~/ftg.git $ ti list
Please run `ti init` to initialize TicGit-ng for this repository before running other ti commands.
```

**Comment by jeffWelling** [comment]
Hm..  Excellent point. 
It might have to do with how much of the information stored in the configuration is global, but there should be some information that could be stored in the repo itself. If there is a way of uniquely identifying a repo then it should be even easier to do.  I'll explore this a bit later after I've finished working on the current release.

**Comment by jeffWelling** [comment]
On further reflection, there is a second problem that you're encountering, TicGit-ng should not be asking you to initialize if all you've done is copied a repository that already had an existing 'ticgit' or 'ticgit-ng' branch.  I'll have to look into this as well.

**Comment by jeffWelling** [comment]
This problem should be resolved in the latest version of TicGit-ng, can you please update your gem and check that it is indeed fixed on your end?
