### ISSUE TITLE
documentation ti new with -t argument

### ISSUE THREAD

**Issue by Erwyn** [jeffWelling/ticgit#79]
Hello,

following our discussion on GChat, this a reminder for clarifying behavior of -t argument with ti new:

ti new -t 'yourtitle'   => will create a ticket with the appropriate title but no description
ti new                       => will prompt editor

Keep up the good work
Amike,

**Comment by jeffWelling** [comment]
Thanks for the reminder!  I'll get to this as soon as I have a chance, but work has me pretty dead right now.
